server:
  port: 8061
  ssl:
    bundle: 'montague'
    client-auth: NEED

spring:
  application.name: ssl-demo
  ssl:
    bundle:
      jks:
        montague:
          key:
            alias: tybalt
          keystore:
            location: ${CERTS_DIR:./local}/montague/tybalt/tybalt.keystore.jks
            password: changeit
            certificate: ${CERTS_DIR:./local}/montague/tybalt/tybalt.crt
          truststore:
            location: ${CERTS_DIR:./local}/montague/montague.truststore.jks
            password: changeit
      pem:
        capulet:
          keystore:
            privateKey: ${CERTS_DIR:./local}/capulet/the-nurse/the-nurse.key
            certificate: ${CERTS_DIR:./local}/capulet/the-nurse/the-nurse.crt
          truststore:
            certificate: ${CERTS_DIR:./local}/capulet/capulet.crt

external:
  montague-url: ${ROMEO_URL:https://localhost:10443}
  capulet-url: ${JULIET_URL:https://localhost:19443}
