version: '3.3'
services:
    ssl-demo:
        image: ssl-demo:latest
        profiles:
            - include-app
        environment:
            CERTS_DIR: /opt/certs
            ROMEO_URL: https://romeo.com
            JULIET_URL: https://juliet.com
        ports:
            - "8061:8061"
        volumes:
            - .:/opt/certs:ro

    romeo.com:
        image: nginx
        ports:
            - "10443:443"
        volumes:
            - ./nginx/romeo-montague.html:/usr/share/nginx/html/index.html
            - ./nginx/romeo-montague.conf:/etc/nginx/conf.d/default.conf
            - ./montague:/etc/ssl/certs/nginx

    juliet.com:
        image: nginx
        ports:
            - "19443:443"
        volumes:
            - ./nginx/juliet-capulet.html:/usr/share/nginx/html/index.html
            - ./nginx/juliet-capulet.conf:/etc/nginx/conf.d/default.conf
            - ./capulet:/etc/ssl/certs/nginx
